# Generated by Django 6.0.5 on 2026-06-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_remove_game_game_type_game_category_game_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
    ]
