# Generated by Django 6.0.5 on 2026-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_game_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_installed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
