# Generated by Django 6.0.5 on 2026-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_rewardcode_userspincredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardcode',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
